### ISSUE TITLE
Trouble getting output in Big Sur and PHP8 on XAMPP

### ISSUE THREAD

**Issue by kidereo** [tmdh/laravel-kit#31]
This looks a very promising and useful app! Thanks!

Unfortunately, I am unable to get output from the code in a tinkering session. All I get is `>>> ... ... ... ` in the output window. The app recognizes PHP version fine.

**Comment by tmdh** [comment]
Can you please test if the issue still exists in master branch?

[Build instructions](https://github.com/tmdh/laravel-kit#development)

**Comment by kidereo** [comment]
I do not have yarn on my dev system, only npm.  Tried installing yarn just now and got all kinds of errors, unfortunately. In the past I downloaded your .dmg release.

Can you update it, please? Would be happy to test. I still use your previous release for artisan commands. Love their implementation. Thanks!

**Comment by tmdh** [comment]
Here,
https://github.com/tmdh/hello-world/releases/download/2.0.5-rc1/Laravel-Kit-2.0.5.dmg

**Comment by kidereo** [comment]
I am getting `Output Error` now. In Settings, php path is set to `/Applications/XAMPP/bin/php` and the app detects PHP version 8.0.10.

**Comment by tmdh** [comment]
Hi,
Can you check if it's fixed in 2.0.5? It works on my mac.

**Comment by kidereo** [comment]
Still no luck on my end, I am afraid. No output error - in fact, there is nothing in the right pane at all. Must be something wrong with my setup. Interestingly, Tinkerun works. 

Regardless, the functionality to list and run artisan commands in your app is very handy. Thank you!

**Comment by tmdh** [comment]
Thank you. Yeah. I didn't test it properly. I'll check on it soon. Will you be available to test the app later on your device?

**Comment by kidereo** [comment]
Certainly. I code with Laravel pretty much on a daily basis. Just give me a shout.

**Comment by tmdh** [comment]
Hi,
Can you please test this build?
https://github.com/tmdh/hello-world/releases/download/2.0.6-rc1/Laravel-Kit-2.0.6.dmg

**Comment by kidereo** [comment]
This seems to be working! I only had a quick look given it is weekend (and I am on PHP7.4 at the moment) but `inspire` quotes come up all right, which was not the case previously.

I am closing this as resolved. Thank you for fixing this!
